name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches-ignore:
      - 'main'
jobs:
  Pylint:
    runs-on: ubuntu-latest
    steps:
   - name: Check .editorconfig
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      run: 
        pip install editorconfig-checker
        editorconfig-checker
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install dependencies
      run: 
        pip install pylint black flake8 markdown-lint-cli
    - name: Analysing the code with pylint
      run: 
        pylint $(git ls-files '*.py')
    - name: Check markdown files
      run: 
        markdownlint-cli .
        
  Initial:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
  
  Build:
    runs-on: ubuntu-latest
    needs: Initial
    steps:
      - run: echo "Build"

  Lint:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - run: echo "Lint"

  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - run: echo "Test"

  Configure-secrets:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Retrieve secret
        env:
          super_secret: ${{ secrets.SUPERSECRET }}
        run: |
          echo "$super_secret"


  Deploy:
    runs-on: ubuntu-latest
    needs: [Lint, Test, Configure-secrets]
    steps:
      - run: echo "Deploy"